### ISSUE TITLE
[Feature request] More granural labels for envsubst

### ISSUE THREAD

**Issue by ondrejkolin** [fluxcd/kustomize-controller#1082]
Introduce some more labels for a bit more granular control of substitution. Right now it's only possible to turn the substitution off on a resource by using the label `kustomize.toolkit.fluxcd.io/substitute: disabled`.

I would welcome an option to specify a JSON path. `kustomize.toolkit.fluxcd.io/substitute-path: .metadata`. would help greatly if you f.e. install complex CRDs which do substitutions on their own on later on. 

Backstory:
We have a horrible CRDs with a JSON as a string inside. This JSON also includes variables which are interpreted by the CRD operator.

**Comment by stefanprodan** [comment]
@ondrejkolin as documented here https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution you can escape vars with`$${var}` and after Flux runs the substitutions, it will result in `${var}`.

**Comment by ondrejkolin** [comment]
That's a fair point. My usecase is ... I export some settings which is a horrific JSON from grafana / whatever for our cloud operator (which uses env substitution too). 

Right now it means, that I have to do preprocessing (sed f.e.) before storing it. 

But you are actually right, that's not a big deal. Thanks for the hint

feel free to close ... :-)

**Comment by stefanprodan** [comment]
Filtering by YAML node can't work with envsubst, as envsubst has no clue about YAML, we stream the bytes to it and it does the replacements line by line.
