### ISSUE TITLE
Please add custom prefix commit message for flux toolkit  as an arguments

### ISSUE THREAD

**Issue by Ayush9955** [fluxcd/kustomize-controller#1087]
flux bootstrap gitlab \
  --token-auth \
  --hostname=https://gitlab.xxx.xyz \
  --owner=devops \
  --repository=gitops \
  --branch=feature/TG-1 \
  --path=clusters/my-cluster
Please enter your GitLab personal access token (PAT):
► connecting to https://gitlab.xxx.xyz
► cloning branch "feature/TG-1" from Git repository "https://gitlab.xxx.xyz/devops/gitops.git"
✔ cloned repository
► generating component manifests
✔ generated component manifests
✔ committed component manifests to "feature/TG-1" ("1dbc2bab0b79d69c9e6eff1a286caf020085faf3")
► pushing component manifests to "https://gitlab.oortfy.xyz/xxxx/gitops.git"
✗ failed to push manifests: failed to push to remote: command error on refs/heads/feature/TG-1: pre-receive hook declined

**Comment by stefanprodan** [comment]
We only support commit appendix which gets added to the commit message as new line at the end:

```
--commit-message-appendix string         string to add to the commit messages, e.g. '[ci skip]'
```

Please open an issue in the [flux2](https://github.com/fluxcd/flux2) repo if this is not sufficient for you.
