### ISSUE TITLE
Kustomization controller throws x509: certificate signed with unknown authority v2.2.3

### ISSUE THREAD

**Issue by sukkola** [fluxcd/kustomize-controller#1137]
Providing the external kubeconfig for applying customisations to external k3s cluster throws. The same setup with two k3d clusters running on the same host seems to be working without a problem, but when external deployment target server is changed into a k3s server running on dedicated host the remote connection fails

```bash
 Warning  ReconciliationFailed  5m46s (x3 over 15m)  kustomize-controller  CustomResourceDefinition/helmcharts.source.toolkit.fluxcd.io dry-run failed: failed to get API group resources: unable to │
│  retrieve the complete list of server APIs: apiextensions.k8s.io/v1: Get "https://k3s-2-1:6443/apis/apiextensions.k8s.io/v1?timeout=30s": tls: failed to verify certificate: x509: certificate signed │
│  by unknown authority
```

```bash
github.com/fluxcd/kustomize-controller/internal/controller.(*KustomizationReconciler).Reconcile\n\tgithub.com/fluxcd/kustomize-controller/internal/controller/kustomization_controller.go:276
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:22
```

The connection url is read correctly from kubeconfig and the ca matches the the one provided by the external cluster

The certificate chain between the ca and and the server certificate should be valid:

```bash
certigo connect  k3s-2-1:6443  --ca=./trusted-certificates/k3s-self-hosted-ca.crt

** TLS Connection **
Version: TLS 1.3
Cipher Suite: AES_128_GCM_SHA256 cipher

Server has requested a client certificate:
Acceptable issuers:
Supported Signature Schemes:
	RSA-PSS with SHA256
	ECDSA with P256 and SHA256
	ED25519
	RSA-PSS with SHA384
	RSA-PSS with SHA512
	RSA-PKCS1 with SHA256
	RSA-PKCS1 with SHA384
	RSA-PKCS1 with SHA512
	ECDSA with P384 and SHA384
	ECDSA with P521 and SHA512
	RSA-PKCS1 with SHA1
	ECDSA with SHA1

** CERTIFICATE 1 **
Valid: 2024-02-24 13:14 UTC to 2025-04-12 09:50 UTC
Subject:
	O=k3s, CN=k3s
Issuer:
	CN=k3s-server-ca@1708780488
DNS Names:
	k3s-2-1, kubernetes, kubernetes.default, kubernetes.default.svc,
	kubernetes.default.svc.cluster.local, localhost
IP Addresses:
	10.43.0.1, 127.0.0.1, 192.168.50.140, 192.168.53.2, ::1

** CERTIFICATE 2 **
Valid: 2024-02-24 13:14 UTC to 2034-02-21 13:14 UTC
Subject:
	CN=k3s-server-ca@1708780488
Issuer:
	CN=k3s-server-ca@1708780488
Warnings:
	Serial number in cert appears to be zero/negative

Found 1 valid certificate chain(s):
[0] CN=k3s
	=> CN=k3s-server-ca@1708780488 [self-signed] 
```
The --insecure-kubeconfig-tls=true or --insecure-kubeconfig-tls options in the startup args do not seem to affect the functionality in anyway. The attempt to reconcile results into same error

**Comment by stefanprodan** [comment]
The `--insecure-kubeconfig-tls` should fix this. Have you added the flag via a patch in the `flux-system/kustomization.yaml`, can you confirm that the flag is set when running `kubectl -n flux-system get deploy/kustomize-controller -o yaml`?

**Comment by sukkola** [comment]
> The `--insecure-kubeconfig-tls` should fix this. Have you added the flag via a patch in the `flux-system/kustomization.yaml`, can you confirm that the flag is set when running `kubectl -n flux-system get deploy/kustomize-controller -o yaml`?
> 
> Also do you have this in the kubeconfig file?
> 
> ```
> - cluster:
>     insecure-skip-tls-verify: true
> ```

The current setup with patching is


```yaml
    spec:
      containers:
      - args:
        - --events-addr=http://notification-controller.flux-system.svc.cluster.local./
        - --watch-all-namespaces=true
        - --log-level=info
        - --log-encoding=json
        - --enable-leader-election
        - --insecure-kubeconfig-tls=true
        - --log-level=debug
```

I've also tried it with just the plain --insecure-kubeconfig-tls without the value set


at least adding the to the kubeconfig file that is used to create the secret:
```yaml
- cluster:
    insecure-skip-tls-verify: true
```

results into "specifying a root certificates file with the insecure flag is not allowed" as an exeuction result for the kustomize-controller run

**Comment by stefanprodan** [comment]
You need to remove `cluster.certificate-authority-data`

**Comment by sukkola** [comment]
Same problem with that one.  The kubeconfig file was malformed with incorrectly formatted line endings. My bad, Thanks for the assistance
