### ISSUE TITLE
Is continueOnError an option for a kustomization?

### ISSUE THREAD

**Issue by migheorghe** [fluxcd/kustomize-controller#1168]
I have a group of independent resources in the same kustomization. If one of the resource is wrongfully configured the entire kustomization will fail. Is there any possibility to deploy all the files in the kustomization even if one fails? The result ao reconciliation can still be !healthy, !ready but the controller should have tried to apply all resources.

thanks

**Comment by stefanprodan** [comment]
> Is there any possibility to deploy all the files in the kustomization even if one fails?

No, Flux reconciler is by design transactional, changing this would require a Flux v3
