### ISSUE TITLE
Having a faulty resource added in the kustomization file, what happens?

### ISSUE THREAD

**Issue by sandupetrasco** [fluxcd/kustomize-controller#1170]
Hello,
I have a kustomization file containing a number of independent resources.
What is the behavior of the reconciliation step if one of the resources is faulty?
Take this customization file as an example:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resource_1.yaml
- resource_2.yaml
- resource_3.yaml
```
Which of the following is true?
1. If **resource_2** is faulty, neither of the 3 resources are reconciled, with the kustomize-controller throwing an error.
2. If **resource_2** is faulty, the **resource_1** is reconciled, but the **resource_2** and **resource_3** are not reconciled, with the kustomize-controller throwing an error.
3. If **resource_2** is faulty, the **resource_1** and **resource_3** is reconciled, with the **resource_2** not being reconciled, and the kustomize-controller throwing an error.

**Comment by sandupetrasco** [comment]
What happens when you have a working kustomization:
```

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resource_1.yaml
- resource_2.yaml
- resource_3.yaml
```
which will reconcile all the 3 resources as expected, and a faulty update of the kustomization takes place, let's say:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resource_1.yaml
- resource_2_faulty.yaml
- resource_3.yaml
```

Does the kustomization-controller use the first kustomization rather than the faulty update? Or it simply tries over and over again to build the updated kustomization with throwing errors every time?
Thanks in advance!

**Comment by stefanprodan** [comment]
You can try this yourself very easily, it will fail forever until you fix it in Git

**Comment by rbojoga** [comment]
Isn't this an issue on Flux if it is not able to fallback to the previously correct Kustomization as it is trying to constantly apply the faulty one?
