### ISSUE TITLE
Feature request: option to skip dry-run

### ISSUE THREAD

**Issue by lennartack** [fluxcd/kustomize-controller#1194]
### Problem
We often encounter a situation in which some resources are bundled together in a Git repo with interdependencies, causing the dry-run of the kustomize-controller to fail. For example, a RoleBinding needed for a Kyverno policy, or some custom resources that depend on a CRD. It is often too cumbersome or undesirable to put these resources in different kustomizations. However, when they are put in the same kustomization, the dry-run fails due to the dependencies, and nothing gets applied.

### Proposed solution
Add an option to a Kustomization to disable the dry-run. We can then temporarily disable the dry-run such that the dependencies are applied.

**Comment by stefanprodan** [comment]
Due to how Flux server-side apply implementation works this is impossible without rewriting the whole thing and changing the behaviour in a breaking way. We'll need Flux v3 for this.
