### ISSUE TITLE
Update SOPS to v3.9.0

### ISSUE THREAD

**Issue by aivanov-citc** [fluxcd/kustomize-controller#1195]
Please, update sops to [v3.9.0](https://github.com/getsops/sops/releases/tag/v3.9.0)

We're really looking forward to this feature:
- Add --mac-only-encrypted to compute MAC only over values which end up encrypted

**Comment by julienkosinski** [comment]
This new version fix lots of CVEs. In my opinion, this should be a priority...
https://github.com/getsops/sops/issues/1453#issuecomment-2166426080

**Comment by stefanprodan** [comment]
@aivanov-citc did you tried the latest SOPS CLI and it didn't work with Flux?

@julienkosinski what makes you think we use the SOPS binary?

**Comment by stefanprodan** [comment]
So `MAC mismatch` is an error returned by kustomize-controller?

**Comment by aivanov-citc** [comment]
@stefanprodan  hmm... very strange, but it works in kustomize-controller.
The question with "mac_only_encrypted" is closed

**Comment by stefanprodan** [comment]
It's not strange, we had support for partially encrypted files since years ago.

**Comment by julienkosinski** [comment]
@stefanprodan I know it's used as a dependency. I admit I have not checked if CVEs still applies, and in what cases and extents, in this very case. Thank you for making me aware of the difference, and sorry for tagging you if it wasn't necessary... :)
