### ISSUE TITLE
Support remote bases from private git repos

### ISSUE THREAD

**Issue by eLco** [fluxcd/kustomize-controller#136]
Hello,

It is possible in kustomize to use remote bases(git repos for example).
It would be cool if kustomize controller could support them too.

Thank you.

**Comment by stefanprodan** [comment]
What makes you think they are not supported?

**Comment by eLco** [comment]
I wasn’t able to find it in docs.
I was trying to use flux kustomize controller with kustomize configuration that includes bases: git://git@repo.com...

and it’s failed, cause it tried to make git clone.

The only possible solution I’ve thought of is to run kustomize in CI with remote base and provide rendered yaml to flux kustomize controller in separate branch.

**Comment by stefanprodan** [comment]
Git is present inside the container so for remote bases that point to public repositories it should work, what error did you get?

**Comment by eLco** [comment]
I’m using private gitlab repo, that’s why it isn’t working then.

**Comment by stefanprodan** [comment]
For private repo you'll have to use CI, and use source-controller with git auth to pull the branch that contains plain yamls or a Kustomize overlay without remote bases.

**Comment by eLco** [comment]
Thank you for the clarification!
