### ISSUE TITLE
Separate image name for arm

### ISSUE THREAD

**Issue by autarchprinceps** [fluxcd/kustomize-controller#173]
Since you have separate images for arm, it is not possible to transparently switch architectures or operate on a mixed arch cluster.
Why don't you use multi arch images? You already use buildx, all it takes is to merge your two separate build workflow steps into one specifying all architectures.

**Comment by stefanprodan** [comment]
It is possible to operator on a mixed arch cluster with `flux install --arch=amd64` or `flux bootstrap --arch=arm64`, the installer pins the Flux controllers to nodes based on arch and os.
