### ISSUE TITLE
Ability to control verbosity of events

### ISSUE THREAD

**Issue by invke** [fluxcd/kustomize-controller#190]
The output of the events of the kustomize-controller quite quickly get too long on medium-sized clusters. This then causes the output in the slack provider from the notification-controller to exceed the [slack message limit](https://api.slack.com/changelog/2018-04-truncating-really-long-messages), truncating the event. This is a pretty easy limit to hit, I'm hitting it with ~200 resources. With any errors located at the end, the most useful information is lost from the message. This relates to an [issue made on the notification-controller](https://github.com/fluxcd/notification-controller/issues/81) but probably better belongs here, as it's caused by the payload of the event sent by the kustomize-controller.

I originally thought it might be a good idea to configure the verbosity of the underlying `kubectl apply` that feeds into the info/error events, but that still doesn't prevent the output of the unchanged resources that floods the output.

Would it be appropriate to filter out lines that have `unchanged`? There are probably better solutions, like some kind of "smarter" message as mentioned by @phillebaba [here](https://github.com/fluxcd/notification-controller/issues/81#issuecomment-736564387), but this to me seems the simplest, albeit depending on the output of `kubectl apply`.

**Comment by stefanprodan** [comment]
> Would it be appropriate to filter out lines that have unchanged?

I think this could work but we should filter the output only when the apply fails.
