### ISSUE TITLE
Garbage Collection Deleting "downstream" Resources

### ISSUE THREAD

**Issue by zacheryph** [fluxcd/kustomize-controller#192]
I am using KubeDB with its helm chart being deployed via Flux. However I am seeing the kustomize controller sometimes delete Service resources related to these. It doesn't seem to happen all the time. I see it happen _sometimes?_ when altering another resource within the same `kustomization.yaml` though I do not know if it happens all the time. Running a reconcile seems to resolve this (or kubedb operator is just fixing it after so long, i dont know.)

* Kustomize Controller: v0.4.0
* KubeDB Operator: v0.15.1

### Kustomize Controller Log
here I altered a setting for the harbor HelmRelease, and in return the KubeDB services were removed (except the `redis` service which remained intact)
> Log entries cleaned up a little bit
```json
{
  "level":"info",
  "ts":"2020-12-04T15:16:01.894Z",
  "logger":"controllers.Kustomization",
  "msg":"
    garbage collection completed:
      Service/registry/postgres deleted
      Service/registry/postgres-pods deleted
      Service/registry/postgres-standby deleted
      Service/registry/redis-pods deleted
    ",
  "kustomization":"flux-system/flux-system"
}

**Comment by stefanprodan** [comment]
kustomize-controller adds a label called `kustomize.toolkit.fluxcd.io/checksum` for all the objects that come from Git, if KubeDB copies that label to other objects, the they will get deleted if KubeDB doesn't update the label value when kustomize-controller applies a new revision.

**Comment by stefanprodan** [comment]
I don't think there is anything to be fixed in kustomize-controller, if KubeDB copies that labels, then you have to disable garbage collection for the KubeDB custom resources... So best is to place those custom resources in a dedicated dir and create a Kustomization object for it with `prune: false`.

**Comment by zacheryph** [comment]
@stefanprodan I would bet that this is what is going on. will look for a ticket in kubedb for this. I did notice all the postgres, and the `redis-pods` replicates the labels but _not_ the `redis` one so it stayed intact.
