### ISSUE TITLE
Support SOPS decryption of ConfigMaps and values other than "(data|stringData)"

### ISSUE THREAD

**Issue by vaskozl** [fluxcd/kustomize-controller#204]
While porting some standard config files which contain some secrets and some common information (traditionally the secrets being template applied with through Puppet's Hieradata), I've wished that I can sops encrypt part of a ConfigMap.

This would allow adding normal yaml config's in mostly plain text, such that one can easily see the non-secrets values and developers can easily change them without re-encrypting the entire config as a secret.

My current solution is to keep ConfigMaps plain text and add support to the application to override the secret field with a ENV variable which is placed in a secret.

I personally find great value in being able to push changes to configs without manually invoking SOPS encryption action, so this would be a welcome enhancement.

**Comment by stefanprodan** [comment]
ConfigMaps are not kept encrypted in ectd, storing secrets in other types than Kubernetes Secret id bad practice in my opinion, while I do understand it's easier to deal with ConfigMap I'm not for implementing such a feature in Flux.

**Comment by Vaskozl** [comment]
The kind of secrets I'm interested in encrypting are stored as plain text in configs in k8s pods and regular non-kubernetes deployments. As such I'm not concerned about the data being encrypted in etcd, which as far as I understand is only encrypted explicitly given https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/. That is, they are things which I don't want to have plain text in git, but aren't secret enough to warrant special handling by the app.

Even then, I believe one of SOPS strengths is that it support partial yaml encryption for defined keys, and supporting partially encrypted stringData would make sense, that way some non-sensitive configuration options can be stored in plain text in git for quick gitops amendment while definitive secrets can be properly encrypted.

Being able to quickly commit a change to git and push it out to all relevant deployments is a big gitops advantage in my mind.

**Comment by Vaskozl** [comment]
```apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
type: kubernetes.io/basic-auth
stringData:
    hostname: my-hostname
    password: ENC[AES256_GCM,data:BeRHAmZjxXspZQ==,iv:lNaHRUE67V3AjVnFPlK6jmUl3AdY98ic+zlM3jR5JFI=,tag:ajOtaeX6SKq3IIvkvWK0/A==,type:str]
sops:
  ...```

Advantages to me:
* Quickly able to see what this secret defines. In this case, only hostname and password.
* Quickly able to see what hostname the service is connecting too. No need to be able to decrypt the secret or peer into the kubernetes resource.
* Quickly able to change the hostname, e.g. if you want to manually fail over to another host with the same password.

Currently, when deploying an application which takes a massive config file with only a few secrets, one has to either encrypt the entire file as a secret, obfuscating it or refactoring the app to support secrets either from env or a separate config file (which I'm not arguing is a bad thing). I think many will resort to encrypting entire configs with parameters which need not be encrypted.

**Comment by Vaskozl** [comment]
After reviewing the code and trying to encrypt both HR's and ConfigMaps partially (for the purposes of sharing non-split-able configmap mounts), it seems that flux is able to decrypt any resource (not just Secrets) and not just `(data|stringData)`, but any subkey (e.g. a HR value). I previously hadn't given this a try since the documentation is quite explicit.

This is also useful for declaring encrypted values in HR without hiding the keys (using values.yaml within a Secret hides the keys).

Unless there is something I'm missing, this is great new and we can close this issue?

**Comment by onedr0p** [comment]
If this is an intentional change, the documentation might need to be updated @stefanprodan ?

**Comment by stefanprodan** [comment]
kustomize-controller can decrypt any manifest that has the API version, Kind and metadata as plain text. Should you use it? I think not, if you have sensitive information that should be in a Secret.
