### ISSUE TITLE
Potential memory leak 

### ISSUE THREAD

**Issue by moikot** [fluxcd/kustomize-controller#207]
Looking at memory consumption of kustomize-controller (Docker image 
ghcr.io/fluxcd/kustomize-controller-arm64:v0.1.0)
I see it gradually grows over time:
![image](https://user-images.githubusercontent.com/38087929/102219281-8d0cfd80-3edf-11eb-9c5a-6f592207b027.png)

I wonder if it's expected and at some point in time it should drop or it's a memory leak.

**Comment by stefanprodan** [comment]
Use our [dashboards](https://toolkit.fluxcd.io/guides/monitoring/) to monitor Flux controllers memory usage, the memory will be reclaimed by the OS when it needs it, this is how Go works. Also you're running a very old version, v0.5 is latest.
