### ISSUE TITLE
GC seems to abandon objects

### ISSUE THREAD

**Issue by nairb774** [fluxcd/kustomize-controller#209]
Looking at https://github.com/fluxcd/kustomize-controller/blob/8296b8e1f1cf497b694b2fd98a0a6658e78c3a77/controllers/kustomization_gc.go#L68 it seems that the GC logic only searches for objects with a known prior checksum, but this seems to leave some objects behind. I unfortunately don't know how it happened, but I definitely have objects that match the `kustomize.toolkit.fluxcd.io/name` and `kustomize.toolkit.fluxcd.io/namespace` labels but do not have the correct `kustomize.toolkit.fluxcd.io/checksum`. I noticed this when we attempted to clean up some previously deployed resources, but they weren't removed.

```
$ kubectl get statefulset -l kustomize.toolkit.fluxcd.io/namespace=flux-system,kustomize.toolkit.fluxcd.io/name=deploy-ns-kafka -L kustomize.toolkit.fluxcd.io/checksum -A
NAMESPACE   NAME                 READY   AGE   CHECKSUM
kafka       connect              3/3     63d   626af1c4a8d9c2ac041f8e6db6a56d53d936c94a
kafka       connect-mongo-test   0/0     40d   e70b56648e95ab4befdf1c82f49ec2c4ff7c53fc
```

(The connect-mongo-test was scaled to 0 long ago, and was only recently cleaned up)

The relevant Kustomization:

```yaml
kind: Kustomization
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kustomize.toolkit.fluxcd.io/v1beta1","kind":"Kustomization","metadata":{"annotations":{},"labels":{"managed-namespace":"kafka","shell-operator":"006-flux-provision"},"name":"deploy-ns-kafka","namespace":"flux-system","ownerReferences":[{"apiVersion":"v1","kind":"Namespace","name":"kafka","uid":"fc483992-68fe-4aa5-8c8d-440607a0fcc6"}]},"spec":{"dependsOn":[{"name":"cluster"}],"interval":"1m","path":"$REMOVED","prune":true,"serviceAccountName":"deploy-ns-kafka","sourceRef":{"kind":"GitRepository","name":"k8s"},"suspend":false}}
  creationTimestamp: "2020-12-14T18:57:02Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 4
  labels:
    managed-namespace: kafka
    shell-operator: 006-flux-provision
  name: deploy-ns-kafka
  namespace: flux-system
  ownerReferences:
  - apiVersion: v1
    kind: Namespace
    name: kafka
    uid: fc483992-68fe-4aa5-8c8d-440607a0fcc6
  resourceVersion: "400510691"
  selfLink: /apis/kustomize.toolkit.fluxcd.io/v1beta1/namespaces/flux-system/kustomizations/deploy-ns-kafka
  uid: 19150bd0-3724-4e82-88eb-682466bc0509
spec:
  dependsOn:
  - name: cluster
  interval: 1m
  path: $REMOVED
  prune: true
  serviceAccountName: deploy-ns-kafka
  sourceRef:
    kind: GitRepository
    name: k8s
  suspend: false
status:
  conditions:
  - lastTransitionTime: "2020-12-15T19:22:07Z"
    message: 'Applied revision: master/fff779623a7025bd01f345c4536b7e367f664fa0'
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
  lastAppliedRevision: master/fff779623a7025bd01f345c4536b7e367f664fa0
  lastAttemptedRevision: master/fff779623a7025bd01f345c4536b7e367f664fa0
  observedGeneration: 4
  snapshot:
    checksum: 626af1c4a8d9c2ac041f8e6db6a56d53d936c94a
    entries:
    - kinds:
        /v1, Kind=Service: Service
        /v1, Kind=ServiceAccount: ServiceAccount
        apps/v1, Kind=Deployment: Deployment
        apps/v1, Kind=StatefulSet: StatefulSet
        autoscaling.k8s.io/v1, Kind=VerticalPodAutoscaler: VerticalPodAutoscaler
        bitnami.com/v1alpha1, Kind=SealedSecret: SealedSecret
        networking.istio.io/v1beta1, Kind=DestinationRule: DestinationRule
        networking.istio.io/v1beta1, Kind=ServiceEntry: ServiceEntry
        networking.istio.io/v1beta1, Kind=Sidecar: Sidecar
        policy/v1beta1, Kind=PodDisruptionBudget: PodDisruptionBudget
        security.istio.io/v1beta1, Kind=PeerAuthentication: PeerAuthentication
      namespace: kafka
```

Should the GC code search for everything with the `kustomize.toolkit.fluxcd.io/name` and `kustomize.toolkit.fluxcd.io/namespace` labels and remove the things with the wrong checksum? That might be a more resilient approach in the face of unknown failures/bugs.

**Comment by nairb774** [comment]
Forgot to mention, we are running 0.4.0 of the kustomize controller. Just saw there is a 0.5.1 - but it doesn't look like any work was done in this area. I'll still upgrade, but it doesn't look like it will fix the abandoned objects.

**Comment by billimek** [comment]
I think I may be seeing the same issue:

* [created](https://github.com/billimek/k8s-gitops/commit/e07e33adb493376d3a788aa90f1694af7af19dce) a yaml file with a `Deployment` that, after syncing, got properly deployed to the cluster
* [deleted](https://github.com/billimek/k8s-gitops/commit/ec44ea3ecfaede35a53c255ac2ca367edd75fda4) the yaml file, pushed, and synced. flux2 correctly garbage-collected this and deleted the deployment - the log indicated as much: (`garbage collection completed: Deployment/nginx-deployment-test deleted`)
* [created](https://github.com/billimek/k8s-gitops/commit/b0b702f0a19d0c8dfe66d255239bf77e0e57063b) a yaml file with a `HelmRelease` that, after syncing, got properly deployed to the cluster
* [deleted](https://github.com/billimek/k8s-gitops/commit/327733cecd7442168ad6fe5dd6f18738c13751b2) the yaml file, pushed, and synced. flux2 **did not garbage collect this** and nothing was logged

The cluster is running flux2 v 0.5.5 and `prune: true` is set in the [`Kustomization` object](https://github.com/billimek/k8s-gitops/blob/master/flux-system/gotk-sync.yaml)

**Comment by stefanprodan** [comment]
The underling problem is with controller-runtime that can't query for custom resources, tracked in #214 

I've reverted controller-runtime to an older version and we'll do a flux2 release with this temporary fix.
