### ISSUE TITLE
HelmRelease, Kustomization DependsOn

### ISSUE THREAD

**Issue by fearlesschenc** [fluxcd/kustomize-controller#242]
Currently HelmRelease only allowed to depends on HelmRelease, Kustomization only allowed to depends on Kustomization.

Is it a better solution if we can remove the type restriction ?

**Comment by stefanprodan** [comment]
> Is it a better solution if we can remove the type restriction ?

This implies a hard coupling between the two APIs (Kustomization and HelmRelease), I am not in favour of this.

You can add HelmReleases to the Kustomization heath checks, this way dependsOn can be used to create a dependency graph between HelmReleases and other Kubernetes objects.
