### ISSUE TITLE
Kustomize kyaml panic on duplicate keys

### ISSUE THREAD

**Issue by jonaskello** [fluxcd/kustomize-controller#243]
I got the kustomizations stuck in "reconciliation in progress". When I checked the logs of the kustomization controller:

```
{"level":"info","ts":"2021-01-18T07:10:57.568Z","logger":"controller.kustomization","msg":"Starting workers","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","worker count":4}
2021/01/18 07:10:59 failed to decode ynode: yaml: unmarshal errors:
  line 21: mapping key "env" already defined at line 18
```

And sure enough there was a yaml file that had the `env` key twice. However it was a bit hard to find which yaml. I have a multi-tenant setup (not sure if that is relevant) and the `env` key was present twice on an app manifest.

I would be nice if flux would error out the kustomization on this instead of hanging on "reconciliation in progress" and present the error on the kustomization object it pertains to.

**Comment by stefanprodan** [comment]
I opened https://github.com/kubernetes-sigs/kustomize/issues/3480
