### ISSUE TITLE
Add substituteFrom from ConfigMap or Secret

### ISSUE THREAD

**Issue by angelnu** [fluxcd/kustomize-controller#274]
The current substitute for DRY within a cluster or Kustomization but it still requires global settings (multiple clusters, multiple Kustomizations) to be duplicated.

So we need a way to keep those common substitutions centralized.

After talking with @stefanprodan in #272 it looks like the best option is to keep global settings in a ConfigMap or Secret. This would also be consistent with the HelmReleases `valueFrom`.

**Comment by angelnu** [comment]
Many thanks @stefanprodan for the quick time-around! Will give it try next (need to find how to use the dev version of flux2)

**Comment by stefanprodan** [comment]
You need to clone the repo and build the container image on your own. Then apply the CRDs from the main brach and replace kustomize-controller image on your cluster.
