### ISSUE TITLE
Ability to control verbosity of validation errors

### ISSUE THREAD

**Issue by laszlocph** [fluxcd/kustomize-controller#277]
This issue has the exact same motivation as https://github.com/fluxcd/kustomize-controller/issues/190

https://github.com/fluxcd/kustomize-controller/issues/190 was resolved by two filter function:
- https://github.com/fluxcd/kustomize-controller/blob/5f966d0ff615658dc630a89837abeb1bf459d75a/controllers/kustomization_controller.go#L645
- https://github.com/fluxcd/kustomize-controller/blob/5f966d0ff615658dc630a89837abeb1bf459d75a/controllers/kustomization_controller.go#L648

and they handle the apply case perfectly.

I would like that the `validate` function gets the same treatment too. https://github.com/fluxcd/kustomize-controller/blob/5f966d0ff615658dc630a89837abeb1bf459d75a/controllers/kustomization_controller.go#L565

There, the kustomize output is returned without any treatment: https://github.com/fluxcd/kustomize-controller/blob/5f966d0ff615658dc630a89837abeb1bf459d75a/controllers/kustomization_controller.go#L601

resulting in a long output, where only the validation error is noteworthy:

```
validation failed: namespace/flux-system configured (dry run)
customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io configured (dry run)
customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io configured (dry run)
customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io configured (dry run)
customresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io configured (dry run)
customresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io configured (dry run)
customresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io configured (dry run)
customresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io configured (dry run)
customresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io configured (dry run)
customresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io configured (dry run)
serviceaccount/helm-controller configured (dry run)
serviceaccount/kustomize-controller configured (dry run)
serviceaccount/notification-controller configured (dry run)
serviceaccount/source-controller configured (dry run)
clusterrole.rbac.authorization.k8s.io/crd-controller-flux-system configured (dry run)
clusterrolebinding.rbac.authorization.k8s.io/cluster-reconciler-flux-system configured (dry run)
clusterrolebinding.rbac.authorization.k8s.io/crd-controller-flux-system configured (dry run)
secret/gitops-repo configured (dry run)
service/fosdem-2021 configured (dry run)
service/notification-controller configured (dry run)
service/source-controller configured (dry run)
service/webhook-receiver configured (dry run)
error: error validating "fffbeaa2-7f24-44ad-9db5-b14f54d552bf.yaml": error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "ima  ge" in io.k8s.api.core.v1.Container; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by laszlocph** [comment]
I'm happy to take a stab at this, if the need is generally accepted by Flux maintainers. I would repurpose the `parseApplyError` function and would take into account that the validation step has`  (dry run)` suffix in each line.

**Comment by stefanprodan** [comment]
@laszlocph thanks! please go ahead
