### ISSUE TITLE
Is there any plan to support  overlays crd?

### ISSUE THREAD

**Issue by LeoLiuYan** [fluxcd/kustomize-controller#279]
As the title said,  if `kustomize controller` has any plan to support `overlays` crd?   Users may store their `kustomization.yaml` and `resources` files to kubernetes crd rather than `git` or `helm`.

**Comment by stefanprodan** [comment]
The Flux Kustomization CRD allows in-line images, namespace, strategic merge and JSON patches, even if there is no `kustomization.yaml` in the source, docs here: https://toolkit.fluxcd.io/components/kustomize/kustomization/#override-kustomize-config

As for `resources`, these come from Flux sources and are mapped with `spec.path`. We have no intention on providing a `resources` field in the Flux Kustomization CRD as it overlaps with the source APIs. We want to extend the source-controller types to allow fetching files over HTTPS e.g. yamls and archives.
