### ISSUE TITLE
Creating resources from base templates that should be ignored

### ISSUE THREAD

**Issue by adam-olema** [fluxcd/kustomize-controller#292]
I'm not sure if this is a usage error or a configuration error.

Given a synced github repo with a structure of:

    /base/kustomization.yaml
    /base/some_resource_template.yaml <-- template, not meant to be instantiated
    /prod_namespace/kustomization.yaml <-- instantiates base/some_resource in `prod` namespace

The `prod_namespace/kustomization.yaml` references `../base` in `resources:`.

The intent here is to create ONE resource in the `prod` namespace based on overlay of the base/some_resource_template.

The problem is that I get TWO resources from `base/some_resource_template.yaml`, one in the `prod` namespace (wanted) and one in the `default` namespace (not wanted).  It seems that flux does not realize that the base resource yaml should be ignored.

Is there some configuration or annotation needed to cause the `base` resources to not be created?  If its in the documentation, I am not seeing it.

I tried the `ignore` attribute of the GitRepository resource, but that just breaks everything as the kustomize controller stops checking out that directory and thus kustomize cannot see the base files and can't build.

**Comment by stefanprodan** [comment]
Please see this example on how to structure your repo https://github.com/fluxcd/flux2-kustomize-helm-example

After bootstrap, you should create Flux Kustomizations and set the path to your overlays, the bases should be outside of the clusters dir so that Flux will not try to sync them.

**Comment by adam-olema** [comment]
Thank you, that is helpful.  A mention in the docs would save future people from stumbling on this same issue.  Also, I would truly love to see a pure Kustomize example of this without the helm pieces, just to simplify it a bit.
