### ISSUE TITLE
Why we are usi so old version of kustomize api

### ISSUE THREAD

**Issue by rverma-nsl** [fluxcd/kustomize-controller#336]
current version: sigs.k8s.io/kustomize/api v0.7.4
Latest available: v0.8.8

With enabling this we can start supporting kustomize 4.x specially cause of this https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.1.0

The ability to change kind is quiet useful.

**Comment by hiddeco** [comment]
See https://github.com/fluxcd/flux2/issues/918 for an overview.
