### ISSUE TITLE
Moving resources deeper into a kustomization hierarchy causes them to be deleted

### ISSUE THREAD

**Issue by apeschel** [fluxcd/kustomize-controller#338]
If you have nested kustomizations, moving a resource into a deeper layer causes flux to delete it and recreate it, rather than just leaving it alone.

Here's an example:

Imagine there are two kustomizations layered as so:

Outer -> Inner

Where outer manages the kustomization resource for inner.

Now imagine there is a some arbitrary resource in outer. If this resource is moved from outer to inner, flux will delete it and cause it to be created.

It would make more sense to me if the resources were just left alone.

An interesting counterpoint is that moving resources up your hierarchy works differently - moving a resource from inner to outer would works as expected. Flux leaves the resource alone.

I suspect this is due to the kustomize controller running each kustomization independently rather than in one bundle, even when they're recursively linked.

**Comment by apeschel** [comment]
I was thinking about this a bit, and it occurred to me that the easiest way to solve this and similar problems may be to only run garbage collection when all the flux CRDs are cleanly reconciled. If there's any errors - garbage collection should probably be disabled automatically.

**Comment by apeschel** [comment]
I've opened a new feature request issue and I'll link it here: https://github.com/fluxcd/kustomize-controller/issues/339

**Comment by stefanprodan** [comment]
Set `prune: false` while you organise your repos.
