### ISSUE TITLE
Feature Request - Garbage Collection only runs when all Kustomizations have cleanly reconciled

### ISSUE THREAD

**Issue by apeschel** [fluxcd/kustomize-controller#339]
At the moment, garbage collection is configured to run pretty aggressively. This leads to a few edge cases where resources can be deleted unintentionally.

Scenario 1: A resource is moved from one kustomization to another. 

Scenario 2: A resource is moved from a parent kustomization to a child kustomization

Scenario 3: A kustomization has an error during reconciliation

In these three scenarios, the garbage collector can and probably will remove resources, despite that probably not being what the user intended.

My proposal would be pretty simple -- if there are any kustomizations pending or errored, garbage collection should not be allowed to run. This should solve the problems of these three scenarios.

**Comment by stefanprodan** [comment]
You could disable garbage collection with `spec.prune: false` when organising your repos. 

>  if there are any kustomizations pending or errored, garbage collection should not be allowed to run.

Each Kustomization reconciliation runs in isolation, this is by design, the only way to create relationships between objects is by using `spec.dependsOn`.
