### ISSUE TITLE
Detect changes/drift through a filtered diff of the apply/prune

### ISSUE THREAD

**Issue by stealthybox** [fluxcd/kustomize-controller#352]
Instead of relying on kubectl apply output to send Object Update Events, we should:
- run kubectl diff first
- parse the output
- remove all objects where only the checksum annotation changed
- use this list for Object Update Events

> Once we do that, we can drop the checksum label, and use the annotation for GC as well. This would be a major improvement for those that have GC enabled, as they will receive events only for the objects where there is an actual drift.
> 
> https://github.com/fluxcd/kustomize-controller/issues/305#issuecomment-848480607

Some behavior that should clarified:
- **Intentional Update**:
  Do we also emit a "Checksum Changed" Event?
  If so, how are Object Prunes included in a change?
- **Drift Correction**:
  Should we generate an Event when the checksum does not change but there is a diff?

There are potentially some performance characteristics in the suggested implementation we should consider:
> Hopefully cache-hits in the apply for all of the objects from the diff will make adding the diff unnoticeable.
> 
> It would be really ideal if the kubectl output had structured diff information already.
I wonder if using kubectl as a library would make this more possible.
> 
> https://github.com/fluxcd/kustomize-controller/issues/305#issuecomment-848516852

**Comment by JaneLiuL** [comment]
This is very good idea actually~
Only one think I am very confuse is :
If the first commit, we generate 4 resource, and apply to cluster by the kustomize-controller.
Then we commit, and remove 3 of them, only 1 resource on the git repository.

Now when we use `kustomize build > output.yaml`, and run `# kubectl  diff -f output.yaml`, it seems there will no any tips for the 3 resource which have been delete from git repository.

So for the  "Object Prunes "，if we don't use the `checksum` label,  could it possible to use the `diff first-output.yaml` second-output.yaml ? If yes, then we need the source-controller to artifact the last output and latest output.yaml.

Please correct me if I am wrong :) .

**Comment by stefanprodan** [comment]
@JaneLiuL the controller knows which objects with get deleted, we need to implement our own GC dry run and append the diff to the apply one.
