### ISSUE TITLE
 interval set time taking too longer

### ISSUE THREAD

**Issue by sairamvoggu1007** [fluxcd/kustomize-controller#355]
flux not applying the changes as Interval set up

**Comment by stefanprodan** [comment]
If you remove the healthChecks how much it takes?

**Comment by sairamvoggu1007** [comment]
I updated healthCheck timeout to 1 min but still the same it's taking too long. not applying the changes as expected interval time.. I have checked the kustomization controller logs it looks good

**Comment by stefanprodan** [comment]
Please post here the controller logs and the size of your Git repository.

**Comment by hiddeco** [comment]
> not applying the changes as expected interval time

This is somewhat a misperception. The interval is used to queue the next reconciliation, this means that if your Kustomize build or the apply takes longer, it will indeed not run every minute, but every minute after the last reconciliation finished.
