### ISSUE TITLE
can we push controller logs to any specific dir by setting an environment variable. I have to push controller logs to splunk

### ISSUE THREAD

**Issue by sairamvoggu1007** [fluxcd/kustomize-controller#358]
can we push controller logs to any specific dir by setting an environment variable. I have to push controller logs to splunk

**Comment by sairamvoggu1007** [comment]
any update on above please?

**Comment by stefanprodan** [comment]
Like all Kubernetes controllers, Flux logs to stderr, see https://github.com/fluxcd/flux2/discussions/963 for some popular logging solutions.
