### ISSUE TITLE
Validation failed - OS thread

### ISSUE THREAD

**Issue by virus2016** [fluxcd/kustomize-controller#363]
Our kustomization controller looks to not be closing processes which in turn crashes the whole worker node. 

```
validation failed: runtime: failed to create new OS thread (have 3 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
runtime stack:
runtime.throw(0x1e0f243, 0x9)
    /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.newosproc(0xc00005e400)
    /usr/local/go/src/runtime/os_linux.go:160 +0x1be
runtime.newm1(0xc00005e400)
    /usr/local/go/src/runtime/proc.go:2124 +0xdd
runtime.newm(0x1f07298, 0xc00004e800, 0x2)
    /usr/local/go/src/runtime/proc.go:2103 +0xa6
runtime.startm(0x0, 0xc00004c001)
    /usr/local/go/src/runtime/proc.go:2334 +0xe5
runtime.wakep()
    /usr/local/go/src/runtime/proc.go:2433 +0x66
runtime.newproc.func1()
    /usr/local/go/src/runtime/proc.go:3985 +0x97
runtime.systemstack(0x46dcf4)
    /usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
    /usr/local/go/src/runtime/proc.go:1246
goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
    /usr/local/go/src/runtime/asm_amd64.s:339 fp=0xc00005a5d0 sp=0xc00005a5c8 pc=0x46de20
runtime.newproc(0x0, 0x1f07168)
    /usr/local/go/src/runtime/proc.go:3978 +0x6e fp=0xc00005a618 sp=0xc00005a5d0 pc=0x44312e
runtime.init.6()
    /usr/local/go/src/runtime/proc.go:264 +0x35 fp=0xc00005a638 sp=0xc00005a618 pc=0x43a8d5
runtime.doInit(0x2def920)
    /usr/local/go/src/runtime/proc.go:6265 +0xec fp=0xc00005a788 sp=0xc00005a638 pc=0x4483ec
runtime.main()
    /usr/local/go/src/runtime/proc.go:174 +0x130 fp=0xc00005a7e0 sp=0xc00005a788 pc=0x43a610
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00005a7e8 sp=0xc00005a7e0 pc=0x46fb21
Show less
revision
main/1f7a78a676d4dde72eafab2622675df35886913f
```

![image](https://user-images.githubusercontent.com/11227384/121568313-7cb18780-ca17-11eb-95a7-c2237036a280.png)

If we let this continue the node becomes unstable and is not able to recover.

**Comment by stefanprodan** [comment]
How did you determine is kustomize-controller that does this and not some other process that's running on your node? The controller does a shell-exec to kubectl for each Kustomization reconciliation and that's about it.

**Comment by virus2016** [comment]
We created another a fresh Kubernetes cluster with flux 2 with imageautomation. It may not be the kustomise controller however we definitely know it’s a flux rooted issue. 

Is there anything we can do to identify the exact issue?

**Comment by stefanprodan** [comment]
What's the ulimit on those node? What kind of cluster is it GKE/EKS/AKS something else?

Also see my previous comment:

> Can you please exec into kustomize-controller container and post here all the running processes after you get that error.

**Comment by virus2016** [comment]
It’s running on DO. I’ll spin up another fresh one today and let it run. It’s takes about a day for it to crash. 

Thanks

**Comment by stefanprodan** [comment]
Ok exec into the Flux pods and run `top` there should be no hanging kubectl processes.

**Comment by virus2016** [comment]
@stefanprodan looks like I have found the issue... Kubernetes 1.20. If I use 1.18, everything works!

Thanks again!
