### ISSUE TITLE
Checksum is not added when turning back `prune: true`

### ISSUE THREAD

**Issue by ViBiOh** [fluxcd/kustomize-controller#375]
# Context

We had one Kustomization for the whole cluster and wanted to break down to one Kustomization per namespace. We turned `prune: false` on the main Kustomization (to avoid deleting the entire cluster). We deleted the main Kustomization and then created one Kustomization per namespace, with `prune: true`.

# Problem

We have deleted resources in GitRepository since but the [Garbage Collection checksum annotation](https://fluxcd.io/docs/components/kustomize/kustomization/#garbage-collection) is not coming back, which seems to not enable deletion of theses resources.

# Expected

When `prune: true` is turned back on, checksum annotation is "re-added" to objects that match given manifests, in order to enable Garbage collection to work as expected.

I don't know if turning on `force: true` on (and then turning back off) could also solve the issue.

**Comment by stefanprodan** [comment]
First setup would be to write a unit test [here](https://github.com/fluxcd/kustomize-controller/blob/main/controllers/kustomization_controller_gc_test.go) to reproduce this.

**Comment by ViBiOh** [comment]
I've just added a test but I don't have yet the machinery for testing it locally.

**Comment by ViBiOh** [comment]
Closing, as mentioned in the related pull-request, the orphan resource was deleted at the same time the Kustomization was switched, and labels were not updated (because no files were pointing at it anymore).
