### ISSUE TITLE
Run ENV Substitution if empty substituted

### ISSUE THREAD

**Issue by oliverbaehler** [fluxcd/kustomize-controller#388]
Hi

I was playing around with variable substitutions. I made heavy use of defaulting mechanisms. Till I noticed, that defaults are not evaluated, when the owning Kustomization does not have any variables substituted. In fact no expression is evaluated. Looking at the code, this condition causes this: https://github.com/fluxcd/kustomize-controller/blob/80ebb792241accf107488603dd747123559d328b/controllers/kustomization_varsub.go#L75

I am not quiet sure if this is on purpose but the expected behavior for me would be if i have a default expression, it should default  if the variable isn't set.  But before trying to change the code I wanted to check with you guys, what you think about it.

**Comment by stefanprodan** [comment]
We can't enable var substitution by default, it needs to be opt-in (defined now as having at least one var). The reason for this is that envsub replaces all vars it finds with string empty and it has the potential to break scripts embedded in configmap and other objects.

**Comment by oliverbaehler** [comment]
Yeah i get that point, but shouldn't such resources, which might have such expressions in them disabled substitution (aka `kustomize.toolkit.fluxcd.io/substitute: disabled`). So I guess the way to work around this, is having something like this:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: shared
spec:
  ...
  postBuild:
    substitute:
      enabled: "true"
```

I guess that works for me, if there's no interest in this change.

**Comment by stefanprodan** [comment]
@oliverbaehler I would welcome a PR to the docs [here](https://github.com/fluxcd/kustomize-controller/blob/main/docs/spec/v1beta1/kustomization.md#variable-substitution) that explains the current behaviour with your example on how to enable substitutions for default values.
