### ISSUE TITLE
Enhance SubstituteFrom to allow crossnamespace

### ISSUE THREAD

**Issue by JaneLiuL** [fluxcd/kustomize-controller#427]
Usually we have some variables to store on secret or configmap, we use the kustomize-controller to sustitue these variable from the secret or configmap.
But the limitation of the kustomize-controller is that now don't support crossnamespace.
So we hope to enhance kustomize-controller for this part.

**Comment by stefanprodan** [comment]
We discuss this in our Flux public meetings and the decision was not to allow cross-namespace references to secrets outside RBAC. The same way Kubernetes doesn't allow a Deployment to mount secrets from other namespaces, so should Flux.
