### ISSUE TITLE
OpenAPI Schema in kustomization.yaml not working

### ISSUE THREAD

**Issue by stoetti** [fluxcd/kustomize-controller#436]
We have our own CRD for deploying our service in k8s and are moving to GitOps principle for deployment. In order to use kustomize at its best we want to use strategic merge for our CRD which makes necessary to provide a custom OpenAPI schema as described here https://github.com/kubernetes-sigs/kustomize/blob/master/examples/customOpenAPIschema.md

Locally executing kustomize build it works as expected. When applied using flux in the cluster it seems that the custom schema is not taken into account.

I put together a sample with a short readme how to reproduce this situation https://github.com/stoetti/kustomize-openapi-sample

**Comment by stoetti** [comment]
Hey @SomtochiAma 

thanks for picking up the issue. I just upgrade the flux version in the cluster and performed a quick retry. Unfortunately with the same error I originally posted.

Here are the versions of my test-environment which runs in the MS Azure Cloud:
* k8s: 1.20.9
* flux: v0.18.3
* kustomize-controller: v0.15.5

**Comment by SomtochiAma** [comment]
I have been unable to replicate this on my end. I tried it on a kind cluster with the same version you posted.

**Comment by stoetti** [comment]
Well I just confirmed that it works when using a kind-Cluster on my side as well to avoid any mistakes in the readme.

Therefore I did a quick retry using a GKE cluster to check if it is an azure-only issue. The result on the GKE cluster is the same as on the Azure Cluster.

Do you have any  suggestion what can be done on my side to provide necessary information (logs,...) to find the source of the issue?

**Comment by SomtochiAma** [comment]
Heyy, Tried this on a GKE Cluster and it worked okay
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:52:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.1600", GitCommit:"ef8e9f64449d73f9824ff5838cea80e21ec6c127", GitTreeState:"clean", BuildDate:"2021-09-06T09:24:20Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

flux version:
```
flux: v0.20.1
helm-controller: v0.12.1
image-reflector-controller: azure-1.0.15
kustomize-controller: v0.16.0
notification-controller: v0.18.1
source-controller: v0.17.1
```

Commands run 
```
flux create source git repo \
  --url=https://github.com/stoetti/kustomize-openapi-sample.git \
  --interval=10m \
  --branch=main
flux create kustomization deploy \
  --source=repo \
  --path="./deploy" \
  --prune=true \
  --interval=10m
```

Result
```
apiVersion: stoetti.github.com/v1
kind: CustomPod
metadata:
  creationTimestamp: "2021-11-11T12:56:39Z"
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: deploy
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  managedFields:
  - apiVersion: stoetti.github.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:kustomize.toolkit.fluxcd.io/name: {}
          f:kustomize.toolkit.fluxcd.io/namespace: {}
      f:spec:
        f:podTemplate:
          f:spec: {}
    manager: kustomize-controller
    operation: Apply
    time: "2021-11-11T12:56:39Z"
  name: test
  namespace: default
  resourceVersion: "1092280"
  uid: 223d2dff-a05b-4391-9391-2dba5dd1c85d
  spec:
  podTemplate:
    spec:
      containers:
      - env:
        - name: env2
          value: value2
        - name: env1
          value: value1
        name: cont1
```

**Comment by stoetti** [comment]
I don't know why, but somehow it worked on my azure cluster. I propably need to investigate this further on my side.

Thanks for rechecking.
