### ISSUE TITLE
File extensions comparisons are case sensitive

### ISSUE THREAD

**Issue by dholbach** [fluxcd/kustomize-controller#476]
From Ada Logics

> In the lines 

https://github.com/fluxcd/kustomize-controller/blob/1e01d800c56ca21e0aaef5d8d1cfc4debb7ed228/controllers/kustomization_generator.go#L164-L167

> A check happens on the file extension for YAML files

> However, the check is case sensitive. We recommend either documenting this or allowing file extensions that are not purely limited to lowercase extensions.

> Recommendation
> Normalise file extensions when processing them to allow uppercase letters in extensions or clarify that files must be lowercase.

**Comment by relu** [comment]
Looking at the [kustomize source code](https://github.com/kubernetes-sigs/kustomize/blob/master/api/konfig/general.go#L10-L16), it seems the list of recognized files only accounts for the lowercase variant.
I wasn't able to find any user-oriented documentation regarding this convention.

Given there's no support upstream for upper or mixed-case variants of the file extension I think it's safe to close this as "won't fix".
