### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/kustomize-controller#49]
Currently the kustomize controller testing is done with Kubernetes Kind and a series of end-to-end tests. We should create unit tests and mock the source controller artifacts server.

The artifacts mock server could be built on top of Go `httptest` with the following features:
- `func new() (port int)`  creates a httptest server and returns the allocated port
- `func artifactFromYaml(path, yaml string) (url string)` creates a tar.gz with the path e.g. `dev/manifests.yaml` and returns the URL in the format `hash(path).tar.gz`

A basic unit test could look like:
- init mock server
- create artifact from an in-memory namespace yaml
- create a GitRepository object with the artifact url set to the one received from the mock server
- create Kustomization object referencing the above source
- start Kustomize reconciler
- wait for the namespace to be created

**Comment by hiddeco** [comment]
Given that the [source-controller](https://github.com/fluxcd/source-controller/) already has [a set of test servers](https://github.com/fluxcd/source-controller/tree/master/internal/testserver), it would likely be best to move the package there from `internal` to `pkg`, and add another mocking server for artifacts there while making use of some of the logic from the [`Storage` utility](https://github.com/fluxcd/source-controller/blob/master/controllers/storage.go#L126).

This way it can be re-used by all other components when they need to mock source artifacts.
