### ISSUE TITLE
variable substitution not possible in secret data

### ISSUE THREAD

**Issue by EikeHens** [fluxcd/kustomize-controller#504]
### Describe the bug

Variable substitution is not working in secret data.

### Steps to reproduce

Use existing secret for substitution:

  postBuild:
    substitute:
      # sample for local configuration
      test: test
    substituteFrom:
      # default solution configuration
      - kind: ConfigMap
        name: score-solution-config
      # cluster specific solution configuration (overwrites the solution configuration)
      - kind: ConfigMap
        name: score-cluster-config
      # add secret for substitution
      - kind: Secret
        name: flux-system

New secret:

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  annotations:
    test: ${domain:=NA}
    user: ${username:=NA}
type: Opaque
data:
  myUserName: ${username:=NA}

### Expected behavior

myUserName should be set to the origin user name.

It works basically for the annotation section, but not for the data section.

Error message: 
Secret/iotcore/my-secret , error: data values must be of type string Namespace/iotcore configured

### OS / Distro

Windows 10

### Flux version

flux: v0.21.1

### Flux check

► checking prerequisites
✗ flux 0.21.1 <0.23.0 (new version is available, please upgrade)
✔ Kubernetes 1.20.4+k3s1 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.12.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.16.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.18.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.17.2
✔ all checks passed

### Git provider

Gitlab

### Container Registry provider

DockerHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomtochiAma** [comment]
Hey @EikeHens ,

Can you try using `stringData` instead of `data` i.e
```
apiVersion: v1
kind: Secret
metadata:
name: my-secret
annotations:
  test: ${domain:=NA}
  user: ${username:=NA}
type: Opaque
stringData:
  myUserName: ${username:=NA}
```

**Comment by EikeHens** [comment]
Thank you for the response. Substitution using stringData works.
