### ISSUE TITLE
server side apply dry-run non-existing namespace

### ISSUE THREAD

**Issue by messiahUA** [fluxcd/kustomize-controller#511]
I have a setup where namespaces are created and managed by helm releases: Kustomization contains HR-namespace and HR-workload.

Everything was working before SSA:

1. HR-workload throws an error (NS doesn't exist)
1. HR-namespace is created in an existing namespace (flux-system)
1. HR-workload succeeds after namespace is created by HR-namespace in a while

After SSA has been introduced this setup is broken because HR-workload causes an error (no NS) and **HR-namespace is not created at all**. If I'm not mistaken this happens early on a dry-run:
https://github.com/fluxcd/pkg/blob/8cab72ed20d0ee4e7252deccc2bc51328aa2b11c/ssa/manager_apply.go#L67

Exactly this error is thrown:
https://github.com/fluxcd/pkg/blob/8cab72ed20d0ee4e7252deccc2bc51328aa2b11c/ssa/manager_diff.go#L108

Of course neither controller nor SSA are aware of helm release purpose and this is clear, but the key problem is that nothing gets applied if any error happens (compared to earlier versions).

I think this is more of an edge case and maybe namespace should never be managed by helm releases, so this issue can be closed if there is no sense to do any changes.

Also, want to note that I'm adding "dependsOn" (and specify HR-namespace) to the HR-workload, but it has no effect in this context at all, so I would suggest to take into account the dependency order of the resources when applying. Basically HR-namespace should be created first and only then HR-workload should be checked and applied.

**Comment by stefanprodan** [comment]
The "namespace not specified" error is not related to the apply oder, have you've set the `metadata.namespace` in your HR?

PS. SSA applies namespaces before any other resource, so I don't think your assumption is correct.

**Comment by messiahUA** [comment]
namespace is set in both HRs

yes, SSA should apply namespaces before any other resource, but the issue here is that namespace is created by HR, so SSA applies only two HRs and one of those HRs refers to non-existent namespace, so error is expected, but as I've mentioned what is not expected compared to previous versions is that second HR is not applied and thus doesn't create a namespace

and by the way, the exact error is:
`HelmRelease/test/test namespace not specified, error: namespaces "test" not found`

**Comment by messiahUA** [comment]
yep, this is one of the solutions, the second one is to apply plain manifests
I agree
it's just frustrating because will require much effort to change everything

and thanks for you replies! :)

**Comment by stefanprodan** [comment]
I think this can be closed, there is no way we can support this type of setup where namespaces come from charts unless you use `spec.dependsOn` and `spec.wait`.

**Comment by messiahUA** [comment]
I would say that it's a bit counter intuitive that dependsOn has no effect during the apply process (because as I've mentioned i'm using dependsOn between HRs), but in general I agree and it's fair enough, it might be not worth to implement

**Comment by stefanprodan** [comment]
> because as I've mentioned i'm using dependsOn between HRs

This controller has no knowledge of HelmRelease, to kustomize-controller a HelmRelease is just as any other Kubernetes object.
