### ISSUE TITLE
Cannot unmarshal duration field to Kustomization struct

### ISSUE THREAD

**Issue by aaron-trout** [fluxcd/kustomize-controller#519]
The `.spec.interval` field is failing to parse into a `time.Duration`. For example:

```go
package main

import (
	"fmt"

	"github.com/fluxcd/kustomize-controller/api/v1beta2"
	"gopkg.in/yaml.v3"
)

func main() {
	input := `---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: foo
  namespace: bar
spec:
  interval: 5m
`

	var kustomization v1beta2.Kustomization
	err := yaml.Unmarshal([]byte(input), &kustomization)
	if err != nil {
		fmt.Println(fmt.Errorf("failed to unmarshal yaml: %w", err))
	}
}
```

Results in:

```bash
$ go run repro.go
failed to unmarshal yaml: yaml: unmarshal errors:
  line 8: cannot unmarshal !!str `5m` into v1.Duration
```

Context is I am trying to build some automation around bumping the version directly in git/CI after some tests have run. This seems to be a required field so I cannot just rely on a default. Not really sure how this can be working inside this repo... I do see some `yaml.Unmarshal()` calls in the codebase 🤔

**Comment by hiddeco** [comment]
Think the issue is with the YAML package you are making use of, the version used by most Kubernetes projects is: https://github.com/kubernetes-sigs/yaml

**Comment by aaron-trout** [comment]
> Think the issue is with the YAML package you are making use of, the version used by most Kubernetes projects is: https://github.com/kubernetes-sigs/yaml

Oh, yes you are right @hiddeco! It works using that library.

TIL - I thought yaml.v2 / yaml.v3 was _the_ way to do YAML in Go!
