### ISSUE TITLE
patchesStrategicMerge not parsed properly

### ISSUE THREAD

**Issue by Robbilie** [fluxcd/kustomize-controller#560]
I am currently using the CRD:
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
```

I tried two different "patchesStrategicMerge":
```
  patchesStrategicMerge:
    - |-
      apiVersion: v1
      kind: Namespace
      $patch: delete
```
and
```
  patchesStrategicMerge:
    - operator-delete-namespace-patch.yaml
```

the kustomization fails in both cases, describe yields:
```
  Warning  error  53s  kustomize-controller  kustomize build failed: trouble configuring builtin PatchStrategicMergeTransformer with config: `
paths:
- manager_auth_proxy_patch.yaml
- '"apiVersion: v1\nkind: Namespace\n$patch: delete"'
`: open /tmp/operator53414576/config/default/"apiVersion: v1\nkind: Namespace\n$patch: delete": no such file or directory
  Warning  error  14s  kustomize-controller  (combined from similar events): kustomize build failed: trouble configuring builtin PatchStrategicMergeTransformer with config: `
```
and
```
  Warning  error  14s  kustomize-controller  (combined from similar events): kustomize build failed: trouble configuring builtin PatchStrategicMergeTransformer with config: `
paths:
- manager_auth_proxy_patch.yaml
- '"operator-delete-namespace-patch.yaml"'
`: open /tmp/operator3498579176/config/default/"operator-delete-namespace-patch.yaml": no such file or directory
```

It seems inline doesnt work at all and it thinks its a file name, for an actual file name it looks like it is wrapping the file name with quotes.

now, this file doesnt actually exist inside the source ref git repo because i was hoping it would use the file next to the Kustomization which references the git repo instead of looking for the file inside the git repo but that makes sense. this is why i need the inline version to work though…

**Comment by stefanprodan** [comment]
Please see the docs on how to use `patches`: https://fluxcd.io/docs/components/kustomize/kustomization/#patches

PS. Flux Kustomizations can't refer to files, all patches must be inline, if you need to use files than place those inside `kustomization.yaml`.

**Comment by Robbilie** [comment]
Yeah I switched to using the patches field, it still doesn't always do what I want but at least it's not an error :)
