### ISSUE TITLE
Typo in controllers/kustomization_controller.go

### ISSUE THREAD

**Issue by ThemeIT** [fluxcd/kustomize-controller#572]
Found a typo in controllers/kustomization_controller.go

L. 762ff "fmt.Errorf("%s is SOPS **encryted**, configuring decryption is required for this secret to be reconciled",
					ssa.FmtUnstructured(u))"

There is a "p" missing.

Should be "encrypted"

**Comment by pjbgf** [comment]
@ThemeIT thank you very much for reporting the misspelling issue. Let us know if you would be willing to propose a PR to fix it and need some help in the process.
