### ISSUE TITLE
Support for helmCharts in kustomize

### ISSUE THREAD

**Issue by n0rad** [fluxcd/kustomize-controller#579]
Some charts do not provide enough values to setup as wanted.
To get around it while still relying on the upstream chart, using kustomize's helmCharts feature allow you to setup specific cases.

To enable helm inside kustomize, `--enable-helm` must be passed to the build command.
Flux build options are hard coded and so helm cannot be enabled.

I saw some discussions around security issues enabling any kind of plugins for fluxV2, but I think the helm case could be treated differently, since helm is directly supported in kustomize and there are also discussions around removing this flags since it was introduced for security reasons that are since then fixed.

Can you support at least enabling helm ?

**Comment by stefanprodan** [comment]
> Some charts do not provide enough values to setup as wanted.

You can use the post-renderer feature to kustomize your Helm releases. Docs here: https://fluxcd.io/docs/components/helm/helmreleases/#post-renderers

**Comment by n0rad** [comment]
Oh I missed that.
Thx, will test it right away

**Comment by stefanprodan** [comment]
Going to close this as wontfix. We have no plans of adding Helm support to kustomize-controller, Flux has a dedicated controller for all things Helm https://github.com/fluxcd/helm-controller
