### ISSUE TITLE
Decode error when using SOPS on TLS certificate

### ISSUE THREAD

**Issue by LukeRH** [fluxcd/kustomize-controller#612]
### Describe the bug

Hi,
I am getting the following error from flux from the kustomization, validation error: "error decoding from json: illegal base64 data at input byte 3" when trying to use a kubenetes TLS secret in flux encypted with SOPS.

Is it valid to use k8s TLS secrets with SOPS and Fluxcd or do i need to use a generic k8s secret with stringdata values for the tls.crt and tls.key entries.

Thanks

### Steps to reproduce

1. kubectl create -n istio-system secret tls https-cert --key="blah.key" --cert="blah.crt" -o yaml > blah.yaml
2. ./sops --encrypt --encrypted-regex '^(data|stringData)$'  --azure-kv https://blah "C:\sops\blah.yaml" > blah.enc.yaml
3. commit blah.enc.yaml to git
4. When flux tries to apply the secret file i get the exception, validation error: "error decoding from json: illegal base64 data at input byte 3"

### Expected behavior

K8s TLS secrets encypted with SOPS can be applied to clusters using Flux

### OS / Distro

Ubuntu 20.04

### Flux version

0.28.4

### Flux check

► checking prerequisites
✗ flux 0.28.4 <0.28.5 (new version is available, please upgrade)
✔ Kubernetes 1.22.6 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.18.2
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.21.2
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.17.1
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.22.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.23.1
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.22.4
✔ all checks passed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
@SomtochiAma can you try to replicate this bug in a unit test?

**Comment by SomtochiAma** [comment]
Hey @LukeRH ,

Can you post what the encrypted file looks like with the sensitive parts stripped out or replaced?

**Comment by LukeRH** [comment]
Hi, Apologies i had misconfigured my Kustomization, it is now working. Thanks for your help

**Comment by TobiasS1402** [comment]
@LukeRH Do you mind sharing your solution? I am facing the same problem.

**Comment by TobiasS1402** [comment]
`The keys of data and stringData must consist of alphanumeric characters, -, _ or .. All key-value pairs in the stringData field are internally merged into the data field. If a key appears in both the data and the stringData field, the value specified in the stringData field takes precedence.` 

I should have read the [Kubernetes secrets documentation](https://kubernetes.io/docs/concepts/configuration/secret/), it is not allowed to have any other characters in the secret field other then alphanumeric, -, _ or . And i tried to set a complicated password like this:

```
stringData:
  adminToken: j!!YcLWn===BTtT5rFqs@WM$qha%%oWa2BEZZAfU__shPn6j9vX
```

**Comment by gandarez** [comment]
I'm having the same error, what was the solution taken @TobiasS1402 @LukeRH?

**Comment by 5cat** [comment]
I had the same issue, and it turns out I just forgot to add the decryption part in `Kustomization` from `kustomize.toolkit.fluxcd.io/v1beta2`
https://fluxcd.io/flux/guides/mozilla-sops/#gitops-workflow
```
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
```

**Comment by mloskot** [comment]
For the record, here is the thread https://github.com/fluxcd/flux2/discussions/3546 about this issue which points out the need of explicit `decryption.provider: sops` .

**Comment by nilzen** [comment]
Sorry to bump an old thread, but I encountered the same issue just now while encrypting a secret with Age. The secret contained:

```yaml
data:
  token: YXN6ZTNxamh2azd2Yzh2OHAyMzZpcW96Nm9iOWJ0Cg==
```

I faced a decryption issue in the cluster, receiving the error "error decoding from JSON: illegal base64 data at input byte 3." However, when I created the secret withstringData and encrypted it in the same way, the cluster decryption worked as expected:
 
 ```yaml
 stringData:
   token: asze3qjhvk7vc8v8p236iqoz6ob9bt
 ```

_This is, of course, not a real token._

**Comment by mloskot** [comment]
@nilzen  Have you checked the issue I referenced in https://github.com/fluxcd/kustomize-controller/issues/612#issuecomment-1485508944 above? There is, I believe, exactly your kind of issue of `data` vs `stringData` addressed in https://github.com/fluxcd/flux2/discussions/3546#discussioncomment-7105448
