### ISSUE TITLE
postBuild converts strings to integers or float

### ISSUE THREAD

**Issue by dwerder** [fluxcd/kustomize-controller#625]
We have an issues with the following variable:

we use a configmap value as followed:
awsAccountId: "0999991" <-- the leading zero is important

With postBuild enabled the result is 999991. We tried

awsAccountId: "0999991"
awsAccountId: '0999991'
awsAccountId: | -
  0999991
awsAccountId: >-
  0999991

**Comment by stefanprodan** [comment]
Fixed in https://github.com/fluxcd/kustomize-controller/pull/1129
