### ISSUE TITLE
postBuild only supports config maps in same namespace

### ISSUE THREAD

**Issue by alexander-matthiesen** [fluxcd/kustomize-controller#659]
Currently we are having the requirement to reference a configMap from a different namespace in the postBuild section.

It looks like this is the limiting factor:

https://github.com/fluxcd/kustomize-controller/blob/566610883702d82e7756afb7c5d1da4bf433a161/controllers/kustomization_varsub.go#L47

Could we open it up to reference configmaps from different namespaces or is this not possible?

**Comment by stefanprodan** [comment]
Cross-namespace references to Secrets and ConfigMaps go against Kubernetes design principles. If Kubernetes will allow a Deployment to "steal" secrets from a different namespace then so will Flux, but I hight doubt this will ever happen.

PS. You can use a Kyverno policy to sync Secrets and ConfigMaps access namespaces: https://kyverno.io/policies/other/sync_secrets/

**Comment by makkes** [comment]
This would open up security issues where a malicious user could use that mechanism to haul in ConfigMaps from other users. Please see https://github.com/fluxcd/kustomize-controller/issues/659#issuecomment-1135737905
