### ISSUE TITLE
Extend kustomize controller health assessment to support HelmReleases

### ISSUE THREAD

**Issue by paulcarlton-ww** [fluxcd/kustomize-controller#68]
If the kustomize controller health assessment was extended to support HelmReleases the kustomize-controller could be used to deploy helmreleases custom resources and detect execution outcome based on HR status. This would enable users to define kustomization custom resources linked by the dependsOn field and sequence deployment of HelmReleases with other object creations.

**Comment by seaneagan** [comment]
Could also consider integrating the [kstatus library](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus) to get coverage for all the resource types it supports, which includes `HelmRelease` v2, since it [supports](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus#the-ready-condition) the `Ready` condition

**Comment by stefanprodan** [comment]
@seaneagan if kstatus waits for a resource to be created before trying to fetch the ready status then we can replace the current implementation.

**Comment by phillebaba** [comment]
I ran some quick tests to see how kstatus behaves in different scenarios with deployments.

I quickly wrote some code that would poll the status of a deployment. I started the polling before the deployment existed, allowed it to reconcile and be ready, then deleted it again.
```
Id: default_dep_apps_Deployment
Status: NotFound
Message: Resource not found
EventType: ResourceUpdateEvent

Id: default_dep_apps_Deployment
Status: InProgress
Message: Available: 0/1
EventType: ResourceUpdateEvent

Id: default_dep_apps_Deployment
Status: Current
Message: Deployment is available. Replicas: 1
EventType: ResourceUpdateEvent

Id: default_dep_apps_Deployment
Status: Current
Message: Deployment is available. Replicas: 1
EventType: ResourceUpdateEvent

Id: default_dep_apps_Deployment
Status: NotFound
Message: Resource not found
EventType: ResourceUpdateEvent
```

It looks like kstatus does what it advertises, as long as the CRD implements the status it expects. Just need to check how it behaves with HelmReleases, but if it has a similar status I guess it should be fine. Using kstatus would be preferable as we would not have to verify if every single CRD works with the health check.

For reference if you want to try this yourself.
```go
package main

import (
	"context"
	"fmt"

	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/discovery"
	"k8s.io/client-go/discovery/cached/memory"
	"k8s.io/client-go/restmapper"
	"sigs.k8s.io/cli-utils/pkg/kstatus/polling"
	"sigs.k8s.io/cli-utils/pkg/object"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/config"
)

func main() {
	cfg := config.GetConfigOrDie()
	reader, err := client.New(cfg, client.Options{})
	if err != nil {
		panic(err)
	}

	identifiers := []object.ObjMetadata{
		{
			GroupKind: schema.GroupKind{
				Group: "apps",
				Kind:  "Deployment",
			},
			Name:      "dep",
			Namespace: "default",
		},
	}

	dc, err := discovery.NewDiscoveryClientForConfig(cfg)
	if err != nil {
		panic(err)
	}
	mapper := restmapper.NewDeferredDiscoveryRESTMapper(memory.NewMemCacheClient(dc))

	poller := polling.NewStatusPoller(reader, mapper)
	opt := polling.Options{
		PollInterval: 2,
	}
	eventsChan := poller.Poll(context.Background(), identifiers, opt)
	for e := range eventsChan {
		fmt.Printf("Id: %v\n", e.Resource.Identifier.String())
		fmt.Printf("Status: %v\n", e.Resource.Status.String())
		fmt.Printf("Message: %v\n", e.Resource.Message)
		fmt.Printf("EventType: %v\n", e.EventType.String())
		fmt.Println()
	}
}
```

**Comment by scottrigby** [comment]
@seaneagan I'm also following this issue you made for the Helm project https://github.com/helm/helm/issues/8661 (which I also like BTW). It may be good to try to align some of this.
