### ISSUE TITLE
Service (serving.knative.dev/v1): failed to create typed patch object .spec.selector: field not declared in schema

### ISSUE THREAD

**Issue by daper** [fluxcd/kustomize-controller#741]
When I try to create a knative service, the controller fails with the following error:
```
Service/default/<name> dry-run failed, error: failed to create typed patch object
(default/<name>; serving.knative.dev/v1, Kind=Service): .spec.selector: field not declared in schema
```

I have other knative services that got applied without any error on the same kustomization, but there is this one that fails and it only differs on the name and the container image... And none of them has a `.spec.selector` field. Also there are no patches on the flux kustomization.

It succeeds with `kubectl apply`. 

I've found similar issues: #699, #532, #464, #454 and #453. But I couldn't relate them.

Kustomization Controller Version: `v0.29.0`

**Comment by stefanprodan** [comment]
Was that objected created on the cluster with kubectl before you added it to Git? To simulate what Flux does, please try: `kubectl apply --server-side --field-manager=flux-client-side-apply -f`

**Comment by daper** [comment]
Thanks for the reply @stefanprodan. I applied the yaml with the command that you wrote and it was successful, but the kustomize-controller still fails with the same error. I also tried to force a reconciliation on the kustomization but fails too.

**Comment by daper** [comment]
Found the issue. It was a kustomize problem. By issuing a `kustomize build .` on the folder and inspecting the resulting yaml. Turns out that my LabelTransformer:
```yaml
commonLabels:
  kustomize.toolkit.fluxcd.io/substitute: disabled
```
is modifying the knative service adding to it the `.spec.selector` key.

I will open an issue to the correspondent project. Closing this.
