### ISSUE TITLE
Why not sync when there is paused-replicas in keda scaleobject?

### ISSUE THREAD

**Issue by debu99** [fluxcd/kustomize-controller#752]
I was testing fluxcd+flagger, i can see the keda scaledobject was added annotation `autoscaling.keda.sh/paused-replicas: 0` by flagger, but why this is not revert by fluxCD? i tried to add another random annotation manually to scaledobject, it is reverted by fluxCD as expected.

**Comment by stefanprodan** [comment]
Because Flux allows changes made by Flagger to take priority, otherwise Flux would undo all the things that Flagger does.

**Comment by stefanprodan** [comment]
Here is the server-side apply library that we use https://github.com/fluxcd/pkg/tree/main/ssa and here it's how we configure it https://github.com/fluxcd/kustomize-controller/blob/main/controllers/kustomization_controller.go#L621
