### ISSUE TITLE
Kustomize controller reconciliation failed and no further applies

### ISSUE THREAD

**Issue by nitharsandvag** [fluxcd/kustomize-controller#756]
Hello,

We have migrated our Flux1 in aks to Flux2 with aks extension, currently we are facing an issue.
If there is an error in yaml file and the kustomize controller is not able to apply, the state becomes to "reconcilation failed" and further commits will not be applied to the cluster. (kubectl get kustomazation -n flux-system)
So flux stop working, but we can see the commits in the source controller logs but no more applies happen to the cluster.
It works again when we fix the commit with the yaml error.

So my question here is, is there a way to say skip errors in yaml and try to apply the new commits to the cluster?

**Comment by stefanprodan** [comment]
> is there a way to say skip errors in yaml and try to apply the new commits to the cluster?

No there is no way to do that, Flux v2 treats commits as transactions, if someone fails to validate nothing is applied. You may want to validate your manifests before they get pushed to the branch, here is a script to do just that: https://github.com/fluxcd/flux2-kustomize-helm-example/blob/main/scripts/validate.sh
