### ISSUE TITLE
Patching Node manifest taints removes existing taints

### ISSUE THREAD

**Issue by MiddleMan5** [fluxcd/kustomize-controller#772]
We're experimenting with using flux to control labels, annotations, and taints for our nodes. It seems like the server side apply field manager isn't getting set correctly for array values and is wiping out taints managed by other controllers.

flux version: v0.30.2
kustomize-controller version: v0.25.0
kubernetes version: 1.23.0

Given the following node patch spec that we want to merge into the existing node definition:

```yaml
apiVersion: v1
kind: Node
metadata:
  name: dev-admiral
  labels:
    ecosystem: platform
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  taints:
    - effect: NoSchedule
      key: migration-safety
```

The resulting managedFields spec for the node after flux has reconciled the manifest becomes:

```yaml
managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kustomize.toolkit.fluxcd.io/prune: {}
          f:kustomize.toolkit.fluxcd.io/ssa: {}
        f:labels:
          f:kustomize.toolkit.fluxcd.io/name: {}
          f:kustomize.toolkit.fluxcd.io/namespace: {}
          f:ecosystem: {}
      f:spec:
        f:taints: {}
    manager: kustomize-controller
    operation: Apply
    time: "2022-11-30T23:01:51Z"
  ...
```

The important part in my mind is the 
```yaml
      f:spec:
        f:taints: {}
```

The existing taints, and I assume any other array field I tried to patch with this approach, are wiped out.

What I would expect to see in the "kustomize-controller" field manager entry is this instead only for the specified taints:
```yaml
      f:spec:
        f:taints:
          k:{"key":"migration-safety"}:
            .: {}
            f:effect: {}
```

**Comment by somtochiama** [comment]
Looking further into this.

From the SSA [enhancement doc](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/555-server-side-apply/README.md#lists)
> Lists can behave in mostly 3 different ways depending on what their actual semantic is. New annotations allow API authors to define this behavior.

> Atomic lists: The list is owned by only one person and can only be entirely replaced. This is the default for lists. It is defined either in Go IDL by prefixing the list with // +listType=atomic, or in the OpenAPI with "x-kubenetes-list-type": "atomic".

It seems the taints field is an atomic one and can be owned by one controller
