### ISSUE TITLE
Feature request: Log skipped objects

### ISSUE THREAD

**Issue by nijave** [fluxcd/kustomize-controller#794]
Flux v1 had the ability to log objects that were skipped from reconciliation (due to having an `ignore` annotation). Flux v2 supports `kustomize.toolkit.fluxcd.io/reconcile: disabled` but doesn't log any messages when resources are skipped because this annotation.

We're planning to have a "Flux Status" dashboard and having this information makes it much easier to see why certain objects might not have applied/updated. This is a common case in our dev environment where people might temporarily disable reconciliation while testing changes before committing them to source control. 

Looks like maybe this is handled in `github.com/fluxcd/pkg/ssa@v0.23.0/manager_apply.gp`:
```go
	if m.shouldSkipApply(object, existingObject, opts) {
		return m.changeSetEntry(object, UnchangedAction), nil
	}
```
so maybe this dependency needs updated to supply the info or log from there

**Comment by kingdonb** [comment]
I think it should be logged at some level, even if it does not go in the default log, as debug or trace level

There is potentially a lot of messages that repeat every time, I can imagine for one Kustomization with many skipped resources there would be a change in log output volume from only one message to as many as hundreds of lines every minute. This would be a disaster. I think should probably be a debug level message.

**Comment by nijave** [comment]
>from only one message to as many as hundreds of lines every minute

This would be fine for our use case. We generally don't want any resources Flux ignored and plan to set log-based alerts (which we could do with Flux v1). It probably makes sense to make these messages opt-in (regardless of what the final log level is)

**Comment by kingdonb** [comment]
It might also make sense to make the "reconcile: disabled" annotation behavior opt-out-able as well.

The design of Flux is for enforcing, so it makes sense that you don't want this behavior to be possible, as sources of truth in the cluster should rarely override the main source of truth in Git. We have a handful of security lockdown options in the configuration guide that prevent users from doing risky things (like remote bases, or cross-namespace references.)

I'd wager from what you say that while logging the behavior when it happens would be good, blocking would be even better?
