### ISSUE TITLE
Update kustomize to v5.0

### ISSUE THREAD

**Issue by larhauga** [fluxcd/kustomize-controller#800]
Hi, I could not find any references to the new kustomize version here.
Kustomize 5.0 has proven to provide a performance boost for us, reducing our build time with ~60% in some cases.

There are some breaking changes though, ref https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0, https://github.com/kubernetes-sigs/kustomize/releases/tag/kyaml%2Fv0.14.0 and https://github.com/kubernetes-sigs/kustomize/releases/tag/api%2Fv0.13.1.

Do you have any plans for a version bump?

**Comment by hiddeco** [comment]
See https://github.com/fluxcd/flux2/issues/3564
