### ISSUE TITLE
persistentVolumeReclaimPolicy field not declared in schema

### ISSUE THREAD

**Issue by crazyelectron-io** [fluxcd/kustomize-controller#804]
When deploying a manifest with a PVC, Service and Deployment using Flux, the following error occurs:
```
PersistentVolumeClaim/default/docker-registry-pvc dry-run failed, error: failed to create typed patch object (default/docker-registry-pvc; /v1, Kind=PersistentVolumeClaim): .spec.persistentVolumeReclaimPolicy: field not declared in schema
```
Removing the `persistentVolumeReclaimPolicy` entry gets rid of the error. It works fine when directly running `kubctl apply` on the PVC manifest.

**Comment by stefanprodan** [comment]
`persistentVolumeReclaimPolicy` is not a property of PersistentVolumeClaim, see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#persistentvolumeclaim-v1-core

**Comment by crazyelectron-io** [comment]
Your right! I mixed up two branches with different PV/PVC manifest when testing this.
Sorry for that. Issue closed...

**Comment by stefanprodan** [comment]
It's unfortunate that kubectl default behaviour is to silently drop invalid fields. To simulate what Flux does, you must use `kubectl apply --server-side --dry-run=server`.
