### ISSUE TITLE
Immutable field detection

### ISSUE THREAD

**Issue by gdziwoki** [fluxcd/kustomize-controller#834]
Before [CEL transition rules](https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/) was a thing, CRDs would use custom admission webhooks for CRD validation.
I have a `Kustomization` that manages a [TargetGroupBinding](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/targetgroupbinding/targetgroupbinding/)
`Kustomization` has `force: true` but when I change an immutable field in the TargetGroupBinding I get an error on my Kustomization syncs:
```
TargetGroupBinding/kube-system/haproxy-ingress-tgb dry-run failed, reason: TargetGroupBinding update may not change these fields: spec.targetGroupARN, error: admission webhook "vtargetgroupbinding.elbv2.k8s.aws" denied the request: TargetGroupBinding update may not change these fields: spec.targetGroupARN
```
Is there any other way to force `kustomize-controller `to recreate those resources?

My env:
Kubernetes EKS 1.24
kustomize-controller v0.31.0

**Comment by stefanprodan** [comment]
We detect immutable errors using Kubernetes `errors` package:

https://github.com/fluxcd/pkg/blob/3a4ad50c09b68efe348532efe393743e82df518c/ssa/utils.go#L287-L295

```go
func IsImmutableError(err error) bool {
	// Detect immutability like kubectl does
	// https://github.com/kubernetes/kubectl/blob/8165f83007/pkg/cmd/apply/patcher.go#L201
	if errors.IsConflict(err) || errors.IsInvalid(err) {
		return true
	}
	return false
}
```

The webhook response doesn't match `IsInvalid`, so there is nothing we can do about it in Flux.

Can you confirm that `kubectl apply --server-side --force` fails the same?

If kubectl fails with `--force`, please open an issue in Kubernetes for them to make the CEL validation error conformant to the Kubernetes conventions. Or maybe they can expose a new `errors` helper to detect CEL immutable errors.

**Comment by gdziwoki** [comment]
It fails with the following error:
```
$ kubectl apply --server-side --force-conflicts -f tgb.yaml
Error from server (TargetGroupBinding update may not change these fields: spec.targetGroupARN): admission webhook "vtargetgroupbinding.elbv2.k8s.aws" denied the request: TargetGroupBinding update may not change these fields: spec.targetGroupARN
```

**Comment by stefanprodan** [comment]
@gdziwoki going to close this issue, we've added immutable error detection to Flux when using CEL or any custom webhook that errors out with `field is immutable`. This doesn't fix the current issue but you can switch to using [CEL](https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/ ) or modify the TargetGroupBinding webhook to return:

```
spec.targetGroupARN is immutable 
```
