### ISSUE TITLE
Apply Label with Source SHA

### ISSUE THREAD

**Issue by Nalum** [fluxcd/kustomize-controller#837]
The controller add's labels to the resources that it manages giving the name and namespace of the kustomize resource. Would it be possible to add another label that notes the sha that the kustomize resource is working with?

**Comment by stefanprodan** [comment]
We have `flux trace` for that, it gives you a full trace back to the source for any Kubernetes object managed by Flux. Adding Git related meta to objects is not something I would consider, Git is just one of many types of sources Flux supports.

**Comment by makkes** [comment]
There's [`.status.lastAppliedRevision`](https://fluxcd.io/flux/components/kustomize/kustomization/#last-applied-revision) and [`.status.lastAttemptedRevision`](https://fluxcd.io/flux/components/kustomize/kustomization/#last-attempted-revision) that gives you the info you're supposedly asking for.

**Comment by Nalum** [comment]
I'll take a look at flux trace and see if this works for the use case.

@makkes what the team is looking for is the Kustomize revision on the `HelmRelease` for example. The `HelmRelease` revision info is the version of the Helm Chart as I understand it.
