### ISSUE TITLE
SOPS AZKV environment variable configuration doesn't work

### ISSUE THREAD

**Issue by apeschel** [fluxcd/kustomize-controller#839]
It looks like a mistake was made in the logic, and the environment variable credentials are retrieved, but never used.

I've opened a PR to address this issue.

https://github.com/fluxcd/kustomize-controller/pull/838

You can refer to this Slack thread for more details: https://cloud-native.slack.com/archives/CLAJ40HV3/p1682102413111849

The SOPS AZKV tests seem to intend to have coverage for configuring auth via environment variables, but something is amiss because the tests seem to be passing even though the functionality is broken.

https://github.com/fluxcd/kustomize-controller/blob/main/internal/sops/azkv/keysource_integration_test.go

**Comment by apeschel** [comment]
Relates to https://github.com/fluxcd/kustomize-controller/issues/841

**Comment by kingdonb** [comment]
Closing with #842 (fixed in Flux 2.0.0-rc.2)
