### ISSUE TITLE
SOPS AZKV test doesn't seem to work

### ISSUE THREAD

**Issue by apeschel** [fluxcd/kustomize-controller#841]
The SOPS AZKV tests seem to intend to have coverage for configuring auth via environment variables, but something is amiss because the tests seem to be passing even though the functionality is broken.

https://github.com/fluxcd/kustomize-controller/blob/main/internal/sops/azkv/keysource_integration_test.go

**Comment by stefanprodan** [comment]
Fixed in https://github.com/fluxcd/kustomize-controller/pull/838
