### ISSUE TITLE
ConfigMap reconcile removes fields not managed by fluxcd

### ISSUE THREAD

**Issue by zhongzhoucai** [fluxcd/kustomize-controller#846]
In my GKE cluster, I used fluxcd to manage my ConfigMap. Then I added a new key-value pair under .data through a manual `kubectl apply --server-side` command, and it succeeded. However, when fluxcd is reconciling the ConfigMap, it removes the new key-value data.

Expected:
Fluxcd only reconciles the fields managed by itself, and leaves the manually added data as is.

Is this WAI?

**Comment by aryan9600** [comment]
you need to specify the flux specific field manager `flux-client-side-apply` or annotate the the ConfigMap with `kustomize.toolkit.fluxcd.io/ssa: merge`. for more details, please see: https://fluxcd.io/flux/components/kustomize/kustomization/#customizing-reconciliation

**Comment by makkes** [comment]
Related to [this Slack discussion](https://cloud-native.slack.com/archives/CLAJ40HV3/p1682413288196099).
