### ISSUE TITLE
Failed to verify archive

### ISSUE THREAD

**Issue by faust64** [fluxcd/kustomize-controller#874]
Hi,

I have a customer ... working with Flux, in a "multi-tenant" way.
Meaning that we have very large clusters. End-users would have access to their own namespaces, operating their own Flux controllers (`--watch-all-namespaces=false`), while we would provide them with CRDs and ClusterRoles.

We recently rolled out some newer flux CRDs (introducing apiversion v1 for gitrepositories or kustomizations, among others).
The latest controllers work just fine (1.0.0-rc.3), as far as I can tell
And while previous apiVersions from those CRDs were un-touched, I would have hoped that customers running older versions of those controllers would not be impacted. And here we were wrong.

We first saw issues with the source-controllers: version 0.25.11 was querying for GitRepositories without specifying the apiVersion, as far as I understand, and started complaining about some "unsupported Git implementation". We could fix that one, runnig source-controller v0.36.1 -- and we can now see some warning, in its logs, complaining that v1beta2 is deprecated, which is expected / that version is indeed deprecated in last CRD schema.

Now, we're getting issues with that kustomize-controller. We are running the last "stable" version to my understanding (v0.35.1)
Status for our kustomization objects would tell about failnig to `verify archive: computed checksup 'aabbccdd' doesn't match provided '' (check whether file siwe exceeds max download size)`.

In this context, we have source-controller 0.36.1, successfully building its artifacts thing and writing it to GitRepository's status. kubectl get gitrepository -o yaml then showing the following (shown observing the served apiVersion for that CRD, which is v1).

```
status:
  artifact:
    digest: sha256:aabbccdd
    lastUpdateTime: xx
    path: gitrepository/namespace/name/12345.tar.gw
    revision: master@sha1:12345
    size: 42
    url: https://source-controlelrs/xxx
...
```

When upgrading kustomize-controller to 1.0.0-rc3, then everything works fine.
Still we didn't plan on asking all our customers to upgrade all at once, un-noticed.

Digging around docs, I did understand operating flux this way is not supported by "the Flux tooling", I'm not sure how we did end up setting up something like this in our context, ... Nor how could we start releasing those last CRD, while matching controllers are still "rc". We fucked up for sure.
Still, I've been discovering your stack while reproducing that issue: it's nice. Coming from Tekton and ArgoCD: Flux sounds interesting as well ... Kudos

Now, I'm left with a few questions moving forward:

 - By any chance: Is there any plan ensure some kind of retro-compatibility, in between flux2 and older flux controllers? Not necessarily old-source/new-kustomize within a same namespace, but from CRD perspective: can we expect multiple instances of flux controllers being lifecycled separately within the same cluster? Should we reconsider our architecture?

 - I am unable to rollback to previous CRD (status.storedVersions somehow shows v1s are already in use everywhere, thus preventing me from just removing it out of my spec.versions array). And am still unclear why are those kustomize-controllers all stuck on that same status. In a lab, I did manage to reproduce, and I'm now trying to switch apiVersion=v1 to served=false, downgrading back to v1beta2: So far, no luck. I don't get it. Anyone knows about those "Failed to verify archive" ? Any way I could work around this?

 - How stable is flux2 today? I can see about 1500 objects  in apigroups toolkit.flux.io, for the two clusters my customers are complaining about right now -- may be a lot more, didn't check yet for full extent of disaster in all clusters ... Would you consider it safe to migrate en masse to that new version just yet? Or should we hold on?

Thanks.

**Comment by stefanprodan** [comment]
@faust64 I recommend you look into setting up [Flux sharding](https://fluxcd.io/flux/cheatsheets/sharding/) which allows you to run multiple instances, all controlled by bootstrap. In your case, you would create a shard per tenant, but without the tenant being responsible for upgrades, as all instances are upgraded as the same time by bootstrap thus avoiding the issues you're having. 

This week we're going to release Flux 2.0 with comes with [backwards compatibility assurances](https://fluxcd.io/flux/releases/) for the GA APIs.
