### ISSUE TITLE
bootstrap: sync path overwrite error for two different directories 

### ISSUE THREAD

**Issue by mjroeleveld** [fluxcd/kustomize-controller#877]
I am trying to upgrade my flux cluster like this.

```
flux bootstrap gitlab \
  --owner=foobar \
  --repository=infrastructure \
  --branch=main \
  --path=foo \
  --token-auth \
  --personal
```

For any path that I enter that _does not_ collide with the existing path, it gives the following error:

```
sync path configuration ("./foo") would overwrite path ("./kustomize/clusters/main") of existing Kustomization
```

This does not make sense to me.

**Comment by mjroeleveld** [comment]
Thanks, I was confused because this is contradicting with the following from the migration docs:

> flux bootstrap should not be run against a Git branch or path that is already being synchronized by Flux v1, as this will make them fight over the resources. Instead, bootstrap to a new Git repository, branch or path, and continue with moving the manifests.

From this I assumed that changing the path is *necessary* to upgrade.

**Comment by mjroeleveld** [comment]
I seem not to understand the versioning of flux and its components. I thought I was upgrading from v1 to v2.

**Comment by stefanprodan** [comment]
Flux v1 is a 5 years old project that we archived in 2022. You are using Flux v2, the upgrade procedure for v2 can be found here: https://fluxcd.io/flux/installation/#upgrade
