### ISSUE TITLE
Unable to use Azure AAD Workload Identity - az binary not found

### ISSUE THREAD

**Issue by paddatrapper** [fluxcd/kustomize-controller#878]
After configuring kustomize-controller to use Azure AAD Workload Identity, reconciliation fails with the following error message:

```
[AZKV]     time="2023-06-01T09:52:00Z" level=error msg="Failed to create Azure authorizer" error="Invoking Azure CLI failed with the following error: exec: \"az\": executable file not found in $PATH"
```

## Steps to reproduce

1. Configure an AAD Workload Identity within Azure
2. Annotate and label the kustomize controller source
3. Restart the kustomize controller pod

This is tested with image `ghcr.io/fluxcd/kustomize-controller:v0.35.1`. The pod has the correct `AZURE_*` environment variables loaded

**Comment by hiddeco** [comment]
Workload Identities are not supported in `v0.35.1`, please update your controller to `>=v1.0.0-rc.2`.

**Comment by paddatrapper** [comment]
Please update the documentation to reflect this requirement - https://fluxcd.io/flux/use-cases/azure/#aad-workload-identity, as it implies that it is supported in the current stable version of flux.

Do you know when v1.0.0 will be released and considered stable?

**Comment by hiddeco** [comment]
The `v1.0.0-rc.*` range is as stable as any `v0.x.y` range. It just means we are moving away from `v0.x.y` while finalizing the last remaining bits.

As noted in [all of our changelogs](https://github.com/fluxcd/flux2/releases): 

> Users are advised to upgrade from older versions [..]

**Comment by paddatrapper** [comment]
That looked to have worked. Thanks
