### ISSUE TITLE
Where is the "controller global decryption" setting?

### ISSUE THREAD

**Issue by lennartack** [fluxcd/kustomize-controller#961]
The docs refer to "controller global decryption". I could not find this mentioned elsewhere or in the code. Does it exist at all?

https://fluxcd.io/flux/components/kustomize/kustomizations/#controller-global-decryption

**Comment by aryan9600** [comment]
"Controller global decryption" is just the name of that section in the docs. There's no such setting, its named as such because decryption is configured at a global level through the kustomize-controller Pod.

**Comment by lennartack** [comment]
> "Controller global decryption" is just the name of that section in the docs. There's no such setting, its named as such because decryption is configured at a global level through the kustomize-controller Pod.

Then what do the docs mean with:
> Other than [authentication using a Secret reference](https://fluxcd.io/flux/components/kustomize/kustomizations/#decryption), it is possible to specify global decryption settings on the kustomize-controller Pod.

I'm looking for the way to specify global decryption settings instead of using a secret reference in a kustomization file.

**Comment by makkes** [comment]
- https://fluxcd.io/flux/components/kustomize/kustomizations/#aws-kms
- https://fluxcd.io/flux/components/kustomize/kustomizations/#azure-key-vault
- https://fluxcd.io/flux/components/kustomize/kustomizations/#gcp-kms
- https://fluxcd.io/flux/components/kustomize/kustomizations/#hashicorp-vault
